/**
 * Codegen Bridge — connects Forgewright to smcraft's code generator.
 *
 * Tries to import from smcraft/codegen and smcraft/parser.
 * If unavailable, provides template-based generation as fallback.
 */

import type { StateMachineDefinition, StateDef, TransitionDef, EventSourceDef } from '../types/smdf';

// ─── smcraft codegen import attempt ──────────────────────────────────────────

type EnrichedModel = {
  definition: StateMachineDefinition;
  stateMap: Map<string, StateDef>;
  eventMap: Map<string, { id: string; name?: string; parameters?: { name: string; type: string }[] }>;
  parentMap: Map<string, string | null>;
  allStates: StateDef[];
  leafStates: StateDef[];
  compositeStates: StateDef[];
};

type SmcraftCodegen = {
  TypeScriptCodeGenerator: new (model: EnrichedModel) => { generate: () => string };
};

type SmcraftParser = {
  enrichModel: (def: StateMachineDefinition) => EnrichedModel;
};

let _codegen: SmcraftCodegen | null = null;
let _parser: SmcraftParser | null = null;
let _importAttempted = false;

async function tryImportSmcraft(): Promise<boolean> {
  if (_importAttempted) return !!(_codegen && _parser);
  _importAttempted = true;
  try {
    const codegenMod = 'smcraft/codegen';
    const parserMod = 'smcraft/parser';
    [_codegen, _parser] = await Promise.all([
      import(/* webpackIgnore: true */ codegenMod) as Promise<SmcraftCodegen>,
      import(/* webpackIgnore: true */ parserMod) as Promise<SmcraftParser>,
    ]);
    return true;
  } catch {
    _codegen = null;
    _parser = null;
    return false;
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

export type CodegenLanguage = 'typescript' | 'python';

/**
 * Generate executable code from an SMDF definition.
 * Tries smcraft codegen first; falls back to template-based generation.
 */
export async function generateCode(
  definition: StateMachineDefinition,
  language: CodegenLanguage = 'typescript',
): Promise<string> {
  const hasSmcraft = await tryImportSmcraft();

  if (hasSmcraft && _codegen && _parser && language === 'typescript') {
    try {
      const enriched = _parser.enrichModel(definition);
      const generator = new _codegen.TypeScriptCodeGenerator(enriched);
      return generator.generate();
    } catch {
      // Fall through to template generation
    }
  }

  // Template-based fallback
  if (language === 'typescript') {
    return generateTypeScriptTemplate(definition);
  }
  return generatePythonTemplate(definition);
}

/**
 * Check which code generation backend is available.
 */
export async function getCodegenBackend(): Promise<'smcraft' | 'template'> {
  const available = await tryImportSmcraft();
  return available ? 'smcraft' : 'template';
}

// ─── Template-based TypeScript Generation ────────────────────────────────────

function generateTypeScriptTemplate(def: StateMachineDefinition): string {
  const name = def.settings.name ?? 'StateMachine';
  const lines: string[] = [];
  const indent = (n: number) => '  '.repeat(n);

  lines.push(`/**`);
  lines.push(` * Generated State Machine: ${name}`);
  lines.push(` * Namespace: ${def.settings.namespace}`);
  lines.push(` * Generated by Forgewright template codegen`);
  lines.push(` */`);
  lines.push('');

  // State enum
  const allStates = collectAllStates(def.state);
  const leafStates = allStates.filter(s => !s.states?.length);

  lines.push(`export enum ${name}State {`);
  for (const state of allStates) {
    lines.push(`${indent(1)}${toConstCase(state.name)} = '${state.name}',`);
  }
  lines.push(`}`);
  lines.push('');

  // Event constants
  const allEvents = collectAllEvents(def.events);
  lines.push(`export const ${name}Events = {`);
  for (const evt of allEvents) {
    lines.push(`${indent(1)}${toConstCase(evt.id)}: '${evt.id}',`);
  }
  lines.push(`} as const;`);
  lines.push('');

  // Transition map type
  lines.push(`export type ${name}Event = typeof ${name}Events[keyof typeof ${name}Events];`);
  lines.push('');

  // Machine class
  lines.push(`export class ${name}Machine {`);
  lines.push(`${indent(1)}private _currentState: ${name}State;`);
  lines.push(`${indent(1)}private _history: ${name}State[] = [];`);
  lines.push(`${indent(1)}private _listeners: Array<(from: ${name}State, to: ${name}State, event: string) => void> = [];`);
  lines.push('');

  // Constructor
  const initial = findInitialLeaf(def.state);
  lines.push(`${indent(1)}constructor() {`);
  lines.push(`${indent(2)}this._currentState = ${name}State.${toConstCase(initial)};`);
  lines.push(`${indent(2)}this._history.push(this._currentState);`);
  lines.push(`${indent(1)}}`);
  lines.push('');

  // Getters
  lines.push(`${indent(1)}get currentState(): ${name}State { return this._currentState; }`);
  lines.push(`${indent(1)}get history(): readonly ${name}State[] { return this._history; }`);
  lines.push('');

  // onTransition
  lines.push(`${indent(1)}onTransition(listener: (from: ${name}State, to: ${name}State, event: string) => void): () => void {`);
  lines.push(`${indent(2)}this._listeners.push(listener);`);
  lines.push(`${indent(2)}return () => { this._listeners = this._listeners.filter(l => l !== listener); };`);
  lines.push(`${indent(1)}}`);
  lines.push('');

  // Fire event
  lines.push(`${indent(1)}fire(event: ${name}Event, context?: Record<string, unknown>): boolean {`);
  lines.push(`${indent(2)}const nextState = this._resolve(event, context);`);
  lines.push(`${indent(2)}if (!nextState) return false;`);
  lines.push(`${indent(2)}const prev = this._currentState;`);
  lines.push(`${indent(2)}this._currentState = nextState;`);
  lines.push(`${indent(2)}this._history.push(nextState);`);
  lines.push(`${indent(2)}for (const l of this._listeners) l(prev, nextState, event);`);
  lines.push(`${indent(2)}return true;`);
  lines.push(`${indent(1)}}`);
  lines.push('');

  // Transition resolver
  lines.push(`${indent(1)}private _resolve(event: string, _context?: Record<string, unknown>): ${name}State | null {`);
  lines.push(`${indent(2)}switch (this._currentState) {`);

  for (const state of leafStates) {
    const transitions = (state.transitions ?? []).filter(t => t.nextState);
    if (transitions.length === 0) continue;

    lines.push(`${indent(3)}case ${name}State.${toConstCase(state.name)}:`);
    for (const t of transitions) {
      const condition = t.condition ? ` && _context?.['${t.condition}']` : '';
      lines.push(`${indent(4)}if (event === '${t.event}'${condition}) return ${name}State.${toConstCase(t.nextState!)};`);
    }
    lines.push(`${indent(4)}break;`);
  }

  lines.push(`${indent(2)}}`);
  lines.push(`${indent(2)}return null;`);
  lines.push(`${indent(1)}}`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ─── Template-based Python Generation ────────────────────────────────────────

function generatePythonTemplate(def: StateMachineDefinition): string {
  const name = def.settings.name ?? 'StateMachine';
  const lines: string[] = [];

  lines.push(`"""`);
  lines.push(`Generated State Machine: ${name}`);
  lines.push(`Namespace: ${def.settings.namespace}`);
  lines.push(`Generated by Forgewright template codegen`);
  lines.push(`"""`);
  lines.push('from enum import Enum');
  lines.push('from typing import Callable, Optional');
  lines.push('');

  // State enum
  const allStates = collectAllStates(def.state);
  const leafStates = allStates.filter(s => !s.states?.length);

  lines.push(`class ${name}State(Enum):`);
  for (const state of allStates) {
    lines.push(`    ${toConstCase(state.name)} = "${state.name}"`);
  }
  lines.push('');

  // Event constants
  const allEvents = collectAllEvents(def.events);
  lines.push(`class ${name}Event:`);
  for (const evt of allEvents) {
    lines.push(`    ${toConstCase(evt.id)} = "${evt.id}"`);
  }
  lines.push('');

  // Machine class
  lines.push(`class ${name}Machine:`);
  lines.push(`    def __init__(self):`);
  const initial = findInitialLeaf(def.state);
  lines.push(`        self._current_state = ${name}State.${toConstCase(initial)}`);
  lines.push(`        self._history: list[${name}State] = [self._current_state]`);
  lines.push(`        self._listeners: list[Callable] = []`);
  lines.push('');

  // Properties
  lines.push(`    @property`);
  lines.push(`    def current_state(self) -> ${name}State:`);
  lines.push(`        return self._current_state`);
  lines.push('');
  lines.push(`    @property`);
  lines.push(`    def history(self) -> list[${name}State]:`);
  lines.push(`        return list(self._history)`);
  lines.push('');

  // on_transition
  lines.push(`    def on_transition(self, listener: Callable) -> Callable:`);
  lines.push(`        self._listeners.append(listener)`);
  lines.push(`        def remove():`);
  lines.push(`            self._listeners.remove(listener)`);
  lines.push(`        return remove`);
  lines.push('');

  // Fire event
  lines.push(`    def fire(self, event: str, context: Optional[dict] = None) -> bool:`);
  lines.push(`        next_state = self._resolve(event, context or {})`);
  lines.push(`        if next_state is None:`);
  lines.push(`            return False`);
  lines.push(`        prev = self._current_state`);
  lines.push(`        self._current_state = next_state`);
  lines.push(`        self._history.append(next_state)`);
  lines.push(`        for listener in self._listeners:`);
  lines.push(`            listener(prev, next_state, event)`);
  lines.push(`        return True`);
  lines.push('');

  // Transition resolver
  lines.push(`    def _resolve(self, event: str, context: dict) -> Optional[${name}State]:`);

  let first = true;
  for (const state of leafStates) {
    const transitions = (state.transitions ?? []).filter(t => t.nextState);
    if (transitions.length === 0) continue;

    const keyword = first ? 'if' : 'elif';
    first = false;
    lines.push(`        ${keyword} self._current_state == ${name}State.${toConstCase(state.name)}:`);

    for (const t of transitions) {
      const condition = t.condition
        ? ` and context.get("${t.condition}")`
        : '';
      lines.push(`            if event == "${t.event}"${condition}:`);
      lines.push(`                return ${name}State.${toConstCase(t.nextState!)}`);
    }
  }

  lines.push(`        return None`);
  lines.push('');

  return lines.join('\n');
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function collectAllStates(root: StateDef): StateDef[] {
  const result: StateDef[] = [];

  function walk(state: StateDef): void {
    result.push(state);
    for (const child of state.states ?? []) walk(child);
  }

  walk(root);
  return result;
}

function collectAllEvents(eventSources: EventSourceDef[]): { id: string; name?: string }[] {
  const seen = new Set<string>();
  const result: { id: string; name?: string }[] = [];

  for (const source of eventSources) {
    for (const evt of source.events ?? []) {
      if (!seen.has(evt.id)) {
        seen.add(evt.id);
        result.push(evt);
      }
    }
  }

  return result;
}

function findInitialLeaf(state: StateDef): string {
  if (state.states && state.states.length > 0) {
    return findInitialLeaf(state.states[0]);
  }
  return state.name;
}

function toConstCase(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .toUpperCase();
}
